<?php /** @var \SR\DeliveryDate\Block\Adminhtml\DeliveryDate $block */ ?>
<div class="admin__field">
    <label for="delivery_date" class="admin__field-label"><span><?= __('Delivery Date') ?></span></label>
    <div class="admin__field-control">
        <input class="admin__control-text <?php if ($block->getRequiredDeliveryDate()): ?> required-entry <?php endif ?>"
               type="text" name="delivery_date" id="delivery_date" readonly="true"/>
    </div>
</div>
<script type="text/javascript">
    require([
        'jquery',
        'mage/calendar'
    ], function ($) {
        $(document).ready(function () {
            var config = <?= $block->getConfig() ?>;
            var disabled = config.shipping.delivery_date.disabled;
            var noday = config.shipping.delivery_date.noday;
            var hourMin = parseInt(config.shipping.delivery_date.hourMin);
            var hourMax = parseInt(config.shipping.delivery_date.hourMax);
            var format = config.shipping.delivery_date.format;
            if(!format) {
                format = 'yy-mm-dd';
            }
            var disabledDay = disabled.split(",").map(function(item) {
                return parseInt(item, 10);
            });

            if(noday) {
                var options = {
                    minDate: 0,
                    dateFormat:format,
                    hourMin: hourMin,
                    hourMax: hourMax
                };
            } else {
                var options = {
                    minDate: 0,
                    dateFormat:format,
                    hourMin: hourMin,
                    hourMax: hourMax,
                    beforeShowDay: function(date) {
                        var day = date.getDay();
                        if(disabledDay.indexOf(day) > -1) {
                            return [false];
                        } else {
                            return [true];
                        }
                    }
                };
            }
            $('#delivery_date').datetimepicker(options);
            console.log('script here');
            $("body").on("click", "#checkout-shipping-method-load .col-method .radio", function(){
                $("#checkout-shipping-method-load .col-method .radio").removeClass("active");
                if($(this).attr("checked") == "checked") {
                    $(this).addClass("active");
                }
            });
        });
    });
</script>
